Circuit breaker
Pliner/aio-request pull request #65
Opened 2021-08-08 08:15 UTC by Pliner

![image](https://user-images.githubusercontent.com/664889/128625675-5c3de8d3-d798-494e-aec3-aea1d15b3914.png)

https://martinfowler.com/bliki/CircuitBreaker.html

2021-08-11 19:10 UTC, Pliner commented on aio_request/base.py
> +    X_CIRCUIT_BREAKER = multidict.istr("X-Circuit-Breaker")
To be able to check in the client that request was produced by Circuit Breaker

2021-08-11 19:11 UTC, Pliner commented on aio_request/base.py
> +    X_DO_NOT_RETRY = multidict.istr("X-Do-Not-Retry")
Do tell a strategy to stop sending requests and accept a response as is

2021-08-12 06:26 UTC, spaceorc requested changes

2021-08-12 06:26 UTC, spaceorc commented on aio_request/circuit_breaker.py
> +    OPENED = "OPENED"
Lets maybe name it OPEN and HALF_OPEN as in article?

2021-08-12 06:26 UTC, spaceorc commented on aio_request/pipeline.py
> +class ByPassModule(RequestModule):
Also suggestion: let's name it BypassModule (small letter 'p')

2021-08-12 06:26 UTC, spaceorc commented on tests/test_circuit_breaker.py
> +async def test_circuit_breaker_should_close_after_failure() -> None:
should_open?

2021-08-12 06:26 UTC, spaceorc commented on aio_request/circuit_breaker.py
> +        failure_threshold: The failure threshold at which the circuit will break (a number between 0 and 1)
Should we check all this limits? E.g. if user passes sampling_duration=0 our RollingCircuitBreakerMetrics will fail...

2021-08-12 06:26 UTC, spaceorc commented on aio_request/circuit_breaker.py
> +        sampling_sampling_duration: The duration when failure ratios are assessed.
typo: sampling_sampling

2021-08-12 06:26 UTC, spaceorc commented on aio_request/circuit_breaker.py
> +        result = await operation()
I'm not sure that we should deal with it somehow, but while we are inside this await there can occur one or more calls to execute with the same scope (e.g. operation can work a lot of time).

2021-08-12 09:13 UTC, spaceorc approved these changes

2021-08-15 09:55 UTC, merged